/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BusinessCard: typeof import('./src/components/BusinessCard.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    HomeView: typeof import('./src/components/HomeView.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    Map: typeof import('./src/components/Map.vue')['default']
    Mower: typeof import('./src/components/Mower.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    QuoteForm: typeof import('./src/components/QuoteForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceAreaView: typeof import('./src/components/ServiceAreaView.vue')['default']
    Services: typeof import('./src/components/Services.vue')['default']
    Splash: typeof import('./src/components/Splash.vue')['default']
  }
}
